import React from 'react';

export const metadata = {
  title: "Privacy Policy | Innoveda",
  description: "Read our privacy policy to understand how we protect your data.",
  alternates: {
    canonical: "https://innoveda.tech/privacy",
  },
};

export default function PrivacyPolicy() {
  return (
    <div className="bg-gray-900 text-white p-8 font-['Inter']">
      <div className="container mx-auto bg-gray-800 p-8 rounded-lg shadow-lg max-w-4xl">
        <h1 className="text-3xl font-bold mb-6">Privacy Policy</h1>
        <p className="text-sm text-gray-400 mb-6">Last updated: July 24, 2025</p>

        <p className="mb-4">This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.</p>
        <p className="mb-6">We use Your Personal Data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy. This Privacy Policy has been created with the help of the <a href="https://www.freeprivacypolicy.com/free-privacy-policy-generator/" className="text-blue-400 hover:underline">Free Privacy Policy Generator</a>, and further adapted for GDPR, CCPA, and AdSense compliance.</p>

        <h2 className="text-2xl font-semibold text-gray-300 mt-8 mb-4">Interpretation and Definitions</h2>

        <h3 className="text-xl font-medium text-gray-400 mb-2">Interpretation</h3>
        <p className="mb-4">The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.</p>

        <h3 className="text-xl font-medium text-gray-400 mb-2">Definitions</h3>
        <p className="mb-4">For the purposes of this Privacy Policy:</p>
        <ul className="list-disc list-inside space-y-2 mb-6 ml-4">
          <li><strong>Account</strong> means a unique account created for You to access our Service or parts of our Service.</li>
          <li><strong>Affiliate</strong> means an entity that controls, is controlled by or is under common control with a party, where &quot;control&quot; means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.</li>
          <li><strong>Company</strong> (referred to as either &quot;the Company&quot;, &quot;We&quot;, &quot;Us&quot; or &quot;Our&quot; in this Agreement) refers to Innoveda.</li>
          <li><strong>Cookies</strong> are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses.</li>
          <li><strong>Country</strong> refers to: Maharashtra, India</li>
          <li><strong>Data Controller</strong>, for the purposes of the GDPR, refers to the Company as the legal person which alone or jointly with others determines the purposes and means of the processing of Personal Data.</li>
          <li><strong>Data Processor</strong> (or Service Provider) means any natural or legal person who processes the data on behalf of the Company.</li>
          <li><strong>Device</strong> means any device that can access the Service such as a computer, a cellphone or a digital tablet.</li>
          <li><strong>Personal Data</strong> is any information that relates to an identified or identifiable individual. Under GDPR, Personal Data also refers to any information relating to You such as a name, an identification number, location data, online identifier or to one or more factors specific to the physical, physiological, genetic, mental, economic, cultural or social identity. Under CCPA, Personal Data means any information that identifies, relates to, describes or is capable of being associated with, or could reasonably be linked, directly or indirectly, with You.</li>
          <li><strong>Service</strong> refers to the Website.</li>
          <li><strong>Service Provider</strong> means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used.</li>
          <li><strong>Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).</li>
          <li><strong>Website</strong> refers to Innoveda, accessible from <a href="https://innoveda.tech" className="text-blue-400 hover:underline">https://innoveda.tech</a>.</li>
          <li><strong>You</strong> means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</li>
        </ul>

        <h2 className="text-2xl font-semibold text-gray-300 mt-8 mb-4">Collecting and Using Your Personal Data</h2>

        <h3 className="text-xl font-medium text-gray-400 mb-2">Types of Data Collected</h3>

        <h4 className="text-lg font-medium text-gray-400 mb-2">Personal Data</h4>
        <p className="mb-4">While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:</p>
        <ul className="list-disc list-inside space-y-2 mb-6 ml-4">
          <li>Email address</li>
          <li>First name and last name</li>
          <li>Phone number</li>
          <li>Address, State, Province, ZIP/Postal code, City</li>
          <li>Usage Data</li>
        </ul>

        <h4 className="text-lg font-medium text-gray-400 mb-2">Usage Data</h4>
        <p className="mb-4">Usage Data is collected automatically when using the Service.</p>
        <p className="mb-4">Usage Data may include information such as Your Device&apos;s Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.</p>
        <p className="mb-4">When You access the Service by or through a mobile device, We may collect certain information automatically, including, but not limited to, the type of mobile device You use, Your mobile device unique ID, the IP address of Your mobile device, Your mobile operating system, the type of mobile Internet browser You use, unique device identifiers and other diagnostic data.</p>
        <p className="mb-6">We may also collect information that Your browser sends whenever You visit our Service or when You access the Service by or through a mobile device.</p>

        <h4 className="text-lg font-medium text-gray-400 mb-2">Tracking Technologies and Cookies</h4>
        <p className="mb-4">We use Cookies and similar tracking technologies to track the activity on Our Service and store certain information. Tracking technologies used are beacons, tags, and scripts to collect and track information and to improve and analyze Our Service. The technologies We use may include:</p>
        <ul className="list-disc list-inside space-y-2 mb-6 ml-4">
          <li><strong>Cookies or Browser Cookies.</strong> A cookie is a small file placed on Your Device. You can instruct Your browser to refuse all Cookies or to indicate when a Cookie is being sent. However, if You do not accept Cookies, You may not be able to use some parts of our Service. Unless you have adjusted Your browser setting so that it will refuse Cookies, our Service may use Cookies.</li>
          <li><strong>Web Beacons.</strong> Certain sections of our Service and our emails may contain small electronic files known as web beacons (also referred to as clear gifs, pixel tags, and single-pixel gifs) that permit the Company, for example, to count users who have visited those pages or opened an email and for other related website statistics (for example, recording the popularity of a certain section and verifying system and server integrity).</li>
        </ul>
        <p className="mb-4">Cookies can be &quot;Persistent&quot; or &quot;Session&quot; Cookies. Persistent Cookies remain on Your personal computer or mobile device when You go offline, while Session Cookies are deleted as soon as You close Your web browser. Learn more about cookies on the <a href="https://www.freeprivacypolicy.com/blog/sample-privacy-policy-template/#Use_Of_Cookies_And_Tracking" className="text-blue-400 hover:underline">Free Privacy Policy website</a> article.</p>
        <p className="mb-4">We use both Session and Persistent Cookies for the purposes set out below:</p>
        <ul className="list-disc list-inside space-y-2 mb-6 ml-4">
          <li>
            <strong>Necessary / Essential Cookies</strong>
            <ul className="list-circle list-inside ml-4 mt-1">
              <li>Type: Session Cookies</li>
              <li>Administered by: Us</li>
              <li>Purpose: These Cookies are essential to provide You with services available through the Website and to enable You to use some of its features. They help to authenticate users and prevent fraudulent use of user accounts. Without these Cookies, the services that You have asked for cannot be provided, and We only use these Cookies to provide You with those services.</li>
            </ul>
          </li>
          <li>
            <strong>Cookies Policy / Notice Acceptance Cookies</strong>
            <ul className="list-circle list-inside ml-4 mt-1">
              <li>Type: Persistent Cookies</li>
              <li>Administered by: Us</li>
              <li>Purpose: These Cookies identify if users have accepted the use of cookies on the Website.</li>
            </ul>
          </li>
          <li>
            <strong>Functionality Cookies</strong>
            <ul className="list-circle list-inside ml-4 mt-1">
              <li>Type: Persistent Cookies</li>
              <li>Administered by: Us</li>
              <li>Purpose: These Cookies allow us to remember choices You make when You use the Website, such as remembering your login details or language preference. The purpose of these Cookies is to provide You with a more personal experience and to avoid You having to re-enter your preferences every time You use the Website.</li>
            </ul>
          </li>
          <li>
            <strong>Advertising / Targeting Cookies</strong>
            <ul className="list-circle list-inside ml-4 mt-1">
              <li>Type: Persistent Cookies</li>
              <li>Administered by: Third-parties (e.g., Google AdSense)</li>
              <li>Purpose: These Cookies are used to deliver advertisements that are more relevant to You and Your interests. They are also used to limit the number of times You see an advertisement and help measure the effectiveness of advertising campaigns. They are usually placed by advertising networks with the website operator&apos;s permission. They remember that You have visited a website and this information is shared with other organizations such as advertisers.</li>
            </ul>
          </li>
        </ul>
        <p className="mb-6">For more information about the cookies we use and your choices regarding cookies, please visit our Cookies Policy or the Cookies section of our Privacy Policy.</p>

        <h3 className="text-xl font-medium text-gray-400 mb-2">Role of the Company as Data Controller and Processor (GDPR)</h3>
        <p className="mb-4">For the purposes of the General Data Protection Regulation (GDPR), Innoveda acts primarily as a <strong>Data Controller</strong> for the Personal Data it collects directly from You for its own defined purposes, such as providing and maintaining the Service, managing Your account, and sending You communications.</p>
        <p className="mb-6">When We utilize third-party Service Providers (e.g., analytics services, advertising networks), these entities may act as <strong>Data Processors</strong> on Our behalf, processing Personal Data strictly according to Our instructions and for the purposes outlined in this Privacy Policy. We ensure that such Service Providers are contractually bound to protect Your data to the same standards as required by GDPR.</p>


        <h3 className="text-xl font-medium text-gray-400 mb-2">Use of Your Personal Data</h3>
        <p className="mb-4">The Company may use Personal Data for the following purposes:</p>
        <ul className="list-disc list-inside space-y-2 mb-6 ml-4">
          <li><strong>To provide and maintain our Service</strong>, including to monitor the usage of our Service.</li>
          <li><strong>To manage Your Account:</strong> to manage Your registration as a user of the Service. The Personal Data You provide can give You access to different functionalities of the Service that are available to You as a registered user.</li>
          <li><strong>For the performance of a contract:</strong> the development, compliance and undertaking of the purchase contract for the products, items or services You have purchased or of any other contract with Us through the Service.</li>
          <li><strong>To contact You:</strong> To contact You by email, telephone calls, SMS, or other equivalent forms of electronic communication, such as a mobile application&apos;s push notifications regarding updates or informative communications related to the functionalities, products or contracted services, including the security updates, when necessary or reasonable for their implementation.</li>
          <li><strong>To provide You</strong> with news, special offers and general information about other goods, services and events which we offer that are similar to those that you have already purchased or enquired about unless You have opted not to receive such information.</li>
          <li><strong>To manage Your requests:</strong> To attend and manage Your requests to Us.</li>
          <li><strong>For business transfers:</strong> We may use Your information to evaluate or conduct a merger, divestiture, restructuring, reorganization, dissolution, or other sale or transfer of some or all of Our assets, whether as a going concern or as part of bankruptcy, liquidation, or similar proceeding, in which Personal Data held by Us about our Service users is among the assets transferred.</li>
          <li><strong>For other purposes</strong>: We may use Your information for other purposes, such as data analysis, identifying usage trends, determining the effectiveness of our promotional campaigns and to evaluate and improve our Service, products, services, marketing and your experience.</li>
        </ul>

        <p className="mb-4">We may share Your personal information in the following situations:</p>
        <ul className="list-disc list-inside space-y-2 mb-6 ml-4">
          <li><strong>With Service Providers:</strong> We may share Your personal information with Service Providers to monitor and analyze the use of our Service, to contact You. This includes third-party analytics providers like Google Analytics and advertising partners like Google AdSense.</li>
          <li><strong>For business transfers:</strong> We may share or transfer Your personal information in connection with, or during negotiations of, any merger, sale of Company assets, financing, or acquisition of all or a portion of Our business to another company.</li>
          <li><strong>With Affiliates:</strong> We may share Your information with Our affiliates, in which case we will require those affiliates to honor this Privacy Policy. Affiliates include Our parent company and any other subsidiaries, joint venture partners or other companies that We control or that are under common control with Us.</li>
          <li><strong>With business partners:</strong> We may share Your information with Our business partners to offer You certain products, services or promotions.</li>
          <li><strong>With other users:</strong> when You share personal information or otherwise interact in the public areas with other users, such information may be viewed by all users and may be publicly distributed outside.</li>
          <li><strong>With Your consent</strong>: We may disclose Your personal information for any other purpose with Your consent.</li>
        </ul>

        <h3 className="text-xl font-medium text-gray-400 mt-8 mb-2">Lawful Basis for Processing Your Personal Data (GDPR)</h3>
        <p className="mb-4">Under GDPR, we process Personal Data based on the following lawful bases:</p>
        <ul className="list-disc list-inside space-y-2 mb-6 ml-4">
          <li><strong>Consent:</strong> We may process Your Personal Data if You have given Your explicit consent for a specific purpose.</li>
          <li><strong>Performance of a contract:</strong> The processing of Personal Data is necessary for the performance of a contract to which You are party or in order to take steps at Your request prior to entering into a contract.</li>
          <li><strong>Legal obligations:</strong> The processing of Personal Data is necessary for compliance with a legal obligation to which the Company is subject.</li>
          <li><strong>Vital interests:</strong> The processing of Personal Data is necessary in order to protect Your vital interests or of another natural person.</li>
          <li><strong>Public interests:</strong> The processing of Personal Data is related to a task that is carried out in the public interest or in the exercise of official authority vested in the Company.</li>
          <li><strong>Legitimate interests:</strong> The processing of Personal Data is necessary for the purposes of the legitimate interests pursued by the Company or by a third party, except where such interests are overridden by Your interests or fundamental rights and freedoms.</li>
        </ul>

        <h3 className="text-xl font-medium text-gray-400 mt-8 mb-2">Retention of Your Personal Data</h3>
        <p className="mb-4">The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use Your Personal Data to the extent necessary to comply with our legal obligations (for example, if we are required to retain your data to comply with applicable laws), resolve disputes, and enforce our legal agreements and policies.</p>
        <p className="mb-6">The Company will also retain Usage Data for internal analysis purposes. Usage Data is generally retained for a shorter period of time, except when this data is used to strengthen the security or to improve the functionality of Our Service, or We are legally obligated to retain this data for longer time periods.</p>

        <h3 className="text-xl font-medium text-gray-400 mt-8 mb-2">Transfer of Your Personal Data</h3>
        <p className="mb-4">Your information, including Personal Data, is processed at the Company&apos;s operating offices and in any other places where the parties involved in the processing are located. It means that this information may be transferred to — and maintained on — computers located outside of Your state, province, country or other governmental jurisdiction where the data protection laws may differ than those from Your jurisdiction.</p>
        <p className="mb-4">Your consent to this Privacy Policy followed by Your submission of such information represents Your agreement to that transfer.</p>
        <p className="mb-6">The Company will take all steps reasonably necessary to ensure that Your data is treated securely and in accordance with this Privacy Policy and no transfer of Your Personal Data will take place to an organization or a country unless there are adequate controls in place including the security of Your data and other personal information.</p>

        <h3 className="text-xl font-medium text-gray-400 mt-8 mb-2">Delete Your Personal Data</h3>
        <p className="mb-4">You have the right to delete or request that We assist in deleting the Personal Data that We have collected about You.</p>
        <p className="mb-4">Our Service may give You the ability to delete certain information about You from within the Service.</p>
        <p className="mb-4">You may update, amend, or delete Your information at any time by signing in to Your Account, if you have one, and visiting the account settings section that allows you to manage Your personal information. You may also contact Us to request access to, correct, or delete any personal information that You have provided to Us.</p>
        <p className="mb-6">Please note, however, that We may need to retain certain information when we have a legal obligation or lawful basis to do so.</p>

        <h3 className="text-xl font-medium text-gray-400 mt-8 mb-2">Disclosure of Your Personal Data</h3>
        <h4 className="text-lg font-medium text-gray-400 mb-2">Business Transactions</h4>
        <p className="mb-4">If the Company is involved in a merger, acquisition or asset sale, Your Personal Data may be transferred. We will provide notice before Your Personal Data is transferred and becomes subject to a different Privacy Policy.</p>

        <h4 className="text-lg font-medium text-gray-400 mb-2">Law enforcement</h4>
        <p className="mb-4">Under certain circumstances, the Company may be required to disclose Your Personal Data if required to do so by law or in response to valid requests by public authorities (e.g. a court or a government agency).</p>

        <h4 className="text-lg font-medium text-gray-400 mb-2">Other legal requirements</h4>
        <p className="mb-4">The Company may disclose Your Personal Data in the good faith belief that such action is necessary to:</p>
        <ul className="list-disc list-inside space-y-2 mb-6 ml-4">
          <li>Comply with a legal obligation</li>
          <li>Protect and defend the rights or property of the Company</li>
          <li>Prevent or investigate possible wrongdoing in connection with the Service</li>
          <li>Protect the personal safety of Users of the Service or the public</li>
          <li>Protect against legal liability</li>
        </ul>

        <h3 className="text-xl font-medium text-gray-400 mt-8 mb-2">Security of Your Personal Data</h3>
        <p className="mb-6">The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While We strive to use commercially acceptable means to protect Your Personal Data, We cannot guarantee its absolute security.</p>

        <h2 className="text-2xl font-semibold text-gray-300 mt-8 mb-4">Your Data Protection Rights (GDPR)</h2>
        <p className="mb-4">If You are a resident of the European Economic Area (EEA) or the UK, You have certain data protection rights. We aim to take reasonable steps to allow You to correct, amend, delete, or limit the use of Your Personal Data. If You wish to be informed what Personal Data We hold about You and if You want it to be removed from Our systems, please contact Us.</p>
        <p className="mb-4">In certain circumstances, You have the following data protection rights:</p>
        <ul className="list-disc list-inside space-y-2 mb-6 ml-4">
          <li><strong>The right to access:</strong> You have the right to request copies of Your Personal Data. We may charge You a small fee for this service.</li>
          <li><strong>The right to rectification:</strong> You have the right to request that We correct any information You believe is inaccurate. You also have the right to request that We complete the information You believe is incomplete.</li>
          <li><strong>The right to erasure:</strong> You have the right to request that We erase Your Personal Data, under certain conditions.</li>
          <li><strong>The right to restrict processing:</strong> You have the right to request that We restrict the processing of Your Personal Data, under certain conditions.</li>
          <li><strong>The right to object to processing:</strong> You have the right to object to Our processing of Your Personal Data, under certain conditions.</li>
          <li><strong>The right to data portability:</strong> You have the right to request that We transfer the data that we have collected to another organization, or directly to You, under certain conditions.</li>
          <li><strong>The right to withdraw consent:</strong> You also have the right to withdraw Your consent at any time where the Company relied on Your consent to process Your personal information.</li>
        </ul>
        <p className="mb-6">You have the right to complain to a Data Protection Authority about Our collection and use of Your Personal Data. For more information, if You are in the European Economic Area (EEA), please contact Your local data protection authority in the EEA.</p>

        <h2 className="text-2xl font-semibold text-gray-300 mt-8 mb-4">CCPA Privacy Rights (Do Not Sell My Personal Information)</h2>
        <p className="mb-4">Under the CCPA, California consumers have the right to:</p>
        <ul className="list-disc list-inside space-y-2 mb-6 ml-4">
          <li>Request that a business that collects a consumer&apos;s personal data disclose the categories and specific pieces of personal data that a business has collected about consumers.</li>
          <li>Request that a business delete any personal data about the consumer that a business has collected.</li>
          <li>Request that a business that sells a consumer&apos;s personal data, not sell the consumer&apos;s personal data.</li>
        </ul>
        <p className="mb-6">If You make a request, We have one month to respond to You. If You would like to exercise any of these rights, please contact Us.</p>

        <h2 className="text-2xl font-semibold text-gray-300 mt-8 mb-4">&quot;Do Not Track&quot; Policy as Required by California Online Privacy Protection Act (CalOPPA)</h2>
        <p className="mb-4">Our Service does not respond to Do Not Track signals. However, some third party websites do keep track of Your browsing activities when they serve You content, which enables them to tailor what they present to You. If You are visiting such websites, Your browser can be set to warn You on DNT signals or to block them. You can enable or disable DNT by visiting the preferences or settings page of Your browser.</p>

        <h2 className="text-2xl font-semibold text-gray-300 mt-8 mb-4">Google AdSense and DoubleClick DART Cookie</h2>
        <p className="mb-4">Google, as a third-party vendor, uses cookies to serve ads on Our Service. Google&apos;s use of the DART cookie enables it to serve ads to Our users based on their visit to Our Service and other sites on the Internet.</p>
        <p className="mb-6">Users may opt out of the use of the DART cookie by visiting the Google Ad and Content Network Privacy Policy at the following URL: <a href="http://www.google.com/privacy_ads.html" className="text-blue-400 hover:underline">http://www.google.com/privacy_ads.html</a></p>
        <p className="mb-6">We use third-party advertising companies to serve ads when you visit our website. These companies may use information (not including your name, address, email address, or telephone number) about your visits to this and other websites in order to provide advertisements about goods and services of interest to you.</p>

        <h2 className="text-2xl font-semibold text-gray-300 mt-8 mb-4">Children&apos;s Privacy</h2>
        <p className="mb-4">Our Service does not address anyone under the age of 13. We do not knowingly collect personally identifiable information from anyone under the age of 13. If You are a parent or guardian and You are aware that Your child has provided Us with Personal Data, please contact Us. If We become aware that We have collected Personal Data from anyone under the age of 13 without verification of parental consent, We take steps to remove that information from Our servers.</p>
        <p className="mb-6">If We need to rely on consent as a legal basis for processing Your information and Your country requires consent from a parent, We may require Your parent&apos;s consent before We collect and use that information.</p>

        <h2 className="text-2xl font-semibold text-gray-300 mt-8 mb-4">Links to Other Websites</h2>
        <p className="mb-4">Our Service may contain links to other websites that are not operated by Us. If You click on a third party link, You will be directed to that third party&apos;s site. We strongly advise You to review the Privacy Policy of every site You visit.</p>
        <p className="mb-6">We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.</p>

        <h2 className="text-2xl font-semibold text-gray-300 mt-8 mb-4">Changes to this Privacy Policy</h2>
        <p className="mb-4">We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page.</p>
        <p className="mb-4">We will let You know via email and/or a prominent notice on Our Service, prior to the change becoming effective and update the &quot;Last updated&quot; date at the top of this Privacy Policy.</p>
        <p className="mb-6">You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.</p>

        <h2 className="text-2xl font-semibold text-gray-300 mt-8 mb-4">Contact Us</h2>
        <p className="mb-4">If you have any questions about this Privacy Policy, You can contact us:</p>
        <ul className="list-disc list-inside mb-6 ml-4">
          <li>By visiting this page on our website: <a href="https://innoveda.tech/contact" className="text-blue-400 hover:underline">https://innoveda.tech/contact</a></li>
          <li>By email: <a href="mailto:privacy@innoveda.tech" className="text-blue-400 hover:underline">privacy@innoveda.tech</a> (for privacy-related inquiries and exercising your data rights)</li>
        </ul>
      </div>
    </div>
  );
};

